### ISSUE TITLE
invokation of dll

### ISSUE THREAD

**Issue by amitbe** [kwart/jd-cmd#10]
hey , im using the api at intellij , when decompiling some apk pop up a message box and waits for user to click 'ok' button ,after debugging i saw that the message comes after invokation of dll file : "libjd-intellij.dll" in the 'native' folder , can i have the dll file source so i can modify it to skip the message box ?
after clicking ok button  the console prints : 
WARN jd.core.output.DirOutput - Class name or java source is null. 
but at the end i do have the ouput decompiled files ... how can i bypass the dialog message ? 
is there a way besides editing the dll file ? and if not i need the dll source so i can modify it.
thanx in advance.

**Comment by kwart** [comment]
I was not the author of natives. I only keep sources for the CLI wrapper. Nevertheless **try the current sources**, which contain no natives. Everything is pure Java!
