### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by naveenkg29** [kwart/jd-cmd#21]
Hi Developer, the build fails due to the repo link not working.

https://raw.github.com/java-decompiler/mvn-repo/master

**Comment by Doudnox** [comment]
Change in file pom.xml
<url>https://raw.github.com/java-decompiler/mvn-repo/master</url>
by
<url>https://raw.github.com/java-decompiler/mvn-repo/master/org/</url>
And it should work.

**Comment by kwart** [comment]
Fixed by #21.
