### ISSUE TITLE
SIGSEGV jvm error

### ISSUE THREAD

**Issue by struktured** [kwart/jd-cmd#8]
Using kubuntu latest.

carm@ultima:~/workspace/ocamljava-maven-plugin-root/bootstrap/ocamljava-2.0-alpha1/lib$ java -jar ~/workspace/jd-cmd/jd-cli/target/jd-cli.jar ocamljava.jar
23:49:17.398 INFO  jd.cli.Main - Decompiling ocamljava.jar
23:49:17.402 INFO  jd.core.output.ZipOutput - ZIP file output will be initialized - ocamljava.src.jar
# 
# A fatal error has been detected by the Java Runtime Environment:
# 
# SIGSEGV (0xb) at pc=0x00007f8c2fcf80fb, pid=26163, tid=140241174370048
# 
# JRE version: Java(TM) SE Runtime Environment (7.0_60-b19) (build 1.7.0_60-b19)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (24.60-b09 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libjd-intellij-tmp3772829641632062216.so+0xcc0fb]  StringToValueMap<unsigned int>::Put(wxString&, unsigned int)+0x41
# 
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
# 
# An error report file with more information is saved as:
# /home/carm/workspace/ocamljava-maven-plugin-root/bootstrap/ocamljava-2.0-alpha1/lib/hs_err_pid26163.log
# 
# If you would like to submit a bug report, please visit:
# http://bugreport.sun.com/bugreport/crash.jsp
# 

Aborted (core dumped)

**Comment by augusting52** [comment]
I got the same problem.Did you solved this problem?

**Comment by augusting52** [comment]
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fc054dc2d69, pid=7013, tid=140464464905984
#
# JRE version: OpenJDK Runtime Environment (8.0_65-b17) (build 1.8.0_65-b17)
# Java VM: OpenJDK 64-Bit Server VM (25.65-b01 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libjd-intellij.so+0xe7d69]  InitStaticFieldsReconstructor::Reconstruct(ClassFile&)+0x16d
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /home/libing/tools/android_package_system/StaticAnalysis/hs_err_pid7013.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.

**Comment by kwart** [comment]
Do you use the latest jd-cli version - `0.9.1`?

https://github.com/kwart/jd-cmd/releases/tag/jd-cmd-0.9.1.Final
